.ifndef REGISTERS_H
REGISTERS_H = 1

.import PPUCTRL, PPUMASK, PPUSTATUS, OAMADDR, OAMDATA, PPUSCROLL, PPUADDR
.import PPUDATA, SQ1_VOL, SQ1_HI, DMC_FREQ, OAMDMA, SND_CHN, JOY2, APU_FRAME
.import OAM

.endif